'use client'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Admin-Dashboard',
  description: 'Generated by create next app',
}
import Menu from '../../components/menuDashbord'
import { 
  Container, 
  MenuContainer, 
  DashboardContent 
} from './style'

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Container>
          <MenuContainer>
            <Menu/>
          </MenuContainer>
          <DashboardContent>
            {children}
          </DashboardContent>
        </Container>
      </body>
    </html>
  )
}
