'use client'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Admin-Dashboard',
  description: 'Generated by create next app',
}
import Menu from '@/components/MenuDashbord'
import FooterDashboard from '@/components/FooterDashboard'
import NavbarDashboard from '@/components/NavbarDashboard'

import { 
  LayoutContainer,
  Container, 
  // MenuContainer, 
  DashboardContent 
} from './style'

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <LayoutContainer>
          <NavbarDashboard/>
          <Container>
            <Menu/>
            <DashboardContent>
              {children}
            </DashboardContent>
          </Container>
          <FooterDashboard/>
        </LayoutContainer>
      </body>
    </html>
  )
}
